hash-format = "sha256"

[[files]]
file = ".github/workflows/release.yml"

[[files]]
file = ".github/workflows/validate.yml"

[[files]]
file = "README.md"

[[files]]
file = "config/Mekanism/client.toml"

[[files]]
file = "config/Mekanism/common.toml"

[[files]]
file = "config/Mekanism/gear.toml"

[[files]]
file = "config/Mekanism/general.toml"

[[files]]
file = "config/Mekanism/generator-storage.toml"

[[files]]
file = "config/Mekanism/generators-gear.toml"

[[files]]
file = "config/Mekanism/generators.toml"

[[files]]
file = "config/Mekanism/machine-storage.toml"

[[files]]
file = "config/Mekanism/machine-usage.toml"

[[files]]
file = "config/Mekanism/startup.toml"

[[files]]
file = "config/Mekanism/tiers.toml"

[[files]]
file = "config/Mekanism/tools-client.toml"

[[files]]
file = "config/Mekanism/tools-materials-startup.toml"

[[files]]
file = "config/Mekanism/tools.toml"

[[files]]
file = "config/Mekanism/world.toml"

[[files]]
file = "config/aiimprovements-common.toml"

[[files]]
file = "config/ars_elemental-client.toml"

[[files]]
file = "config/ars_elemental-common.toml"

[[files]]
file = "config/ars_elemental-startup.toml"

[[files]]
file = "config/ars_elemental/glyph_aerial_filter.toml"

[[files]]
file = "config/ars_elemental/glyph_aquatic_filter.toml"

[[files]]
file = "config/ars_elemental/glyph_arc_projectile.toml"

[[files]]
file = "config/ars_elemental/glyph_bubble_shield.toml"

[[files]]
file = "config/ars_elemental/glyph_cauterize.toml"

[[files]]
file = "config/ars_elemental/glyph_cavitate.toml"

[[files]]
file = "config/ars_elemental/glyph_charm.toml"

[[files]]
file = "config/ars_elemental/glyph_conflagrate.toml"

[[files]]
file = "config/ars_elemental/glyph_conjure_terrain.toml"

[[files]]
file = "config/ars_elemental/glyph_discharge.toml"

[[files]]
file = "config/ars_elemental/glyph_envenom.toml"

[[files]]
file = "config/ars_elemental/glyph_fiery_filter.toml"

[[files]]
file = "config/ars_elemental/glyph_geyser.toml"

[[files]]
file = "config/ars_elemental/glyph_homing_projectile.toml"

[[files]]
file = "config/ars_elemental/glyph_insect_filter.toml"

[[files]]
file = "config/ars_elemental/glyph_life_link.toml"

[[files]]
file = "config/ars_elemental/glyph_mist.toml"

[[files]]
file = "config/ars_elemental/glyph_not_aerial_filter.toml"

[[files]]
file = "config/ars_elemental/glyph_not_aquatic_filter.toml"

[[files]]
file = "config/ars_elemental/glyph_not_fiery_filter.toml"

[[files]]
file = "config/ars_elemental/glyph_not_insect_filter.toml"

[[files]]
file = "config/ars_elemental/glyph_not_summon_filter.toml"

[[files]]
file = "config/ars_elemental/glyph_not_undead_filter.toml"

[[files]]
file = "config/ars_elemental/glyph_nullify_defense.toml"

[[files]]
file = "config/ars_elemental/glyph_oxidize.toml"

[[files]]
file = "config/ars_elemental/glyph_phantom_grasp.toml"

[[files]]
file = "config/ars_elemental/glyph_poison_spores.toml"

[[files]]
file = "config/ars_elemental/glyph_propagator_arc.toml"

[[files]]
file = "config/ars_elemental/glyph_propagator_homing.toml"

[[files]]
file = "config/ars_elemental/glyph_rage.toml"

[[files]]
file = "config/ars_elemental/glyph_slip_feet.toml"

[[files]]
file = "config/ars_elemental/glyph_spark.toml"

[[files]]
file = "config/ars_elemental/glyph_spike.toml"

[[files]]
file = "config/ars_elemental/glyph_summon_bee.toml"

[[files]]
file = "config/ars_elemental/glyph_summon_filter.toml"

[[files]]
file = "config/ars_elemental/glyph_summon_slime.toml"

[[files]]
file = "config/ars_elemental/glyph_undead_filter.toml"

[[files]]
file = "config/ars_elemental/glyph_water_jet.toml"

[[files]]
file = "config/ars_elemental/glyph_watery_grave.toml"

[[files]]
file = "config/ars_nouveau-client.toml"

[[files]]
file = "config/ars_nouveau-common.toml"

[[files]]
file = "config/ars_nouveau-server.toml"

[[files]]
file = "config/ars_nouveau-startup.toml"

[[files]]
file = "config/ars_nouveau/doc_data.json"

[[files]]
file = "config/ars_nouveau/glyph_accelerate.toml"

[[files]]
file = "config/ars_nouveau/glyph_amplify.toml"

[[files]]
file = "config/ars_nouveau/glyph_animate_block.toml"

[[files]]
file = "config/ars_nouveau/glyph_aoe.toml"

[[files]]
file = "config/ars_nouveau/glyph_blink.toml"

[[files]]
file = "config/ars_nouveau/glyph_bounce.toml"

[[files]]
file = "config/ars_nouveau/glyph_break.toml"

[[files]]
file = "config/ars_nouveau/glyph_bubble.toml"

[[files]]
file = "config/ars_nouveau/glyph_burst.toml"

[[files]]
file = "config/ars_nouveau/glyph_cold_snap.toml"

[[files]]
file = "config/ars_nouveau/glyph_conjure_water.toml"

[[files]]
file = "config/ars_nouveau/glyph_craft.toml"

[[files]]
file = "config/ars_nouveau/glyph_crush.toml"

[[files]]
file = "config/ars_nouveau/glyph_cut.toml"

[[files]]
file = "config/ars_nouveau/glyph_dampen.toml"

[[files]]
file = "config/ars_nouveau/glyph_decelerate.toml"

[[files]]
file = "config/ars_nouveau/glyph_delay.toml"

[[files]]
file = "config/ars_nouveau/glyph_dispel.toml"

[[files]]
file = "config/ars_nouveau/glyph_duration_down.toml"

[[files]]
file = "config/ars_nouveau/glyph_ender_inventory.toml"

[[files]]
file = "config/ars_nouveau/glyph_evaporate.toml"

[[files]]
file = "config/ars_nouveau/glyph_exchange.toml"

[[files]]
file = "config/ars_nouveau/glyph_explosion.toml"

[[files]]
file = "config/ars_nouveau/glyph_extend_time.toml"

[[files]]
file = "config/ars_nouveau/glyph_extract.toml"

[[files]]
file = "config/ars_nouveau/glyph_fangs.toml"

[[files]]
file = "config/ars_nouveau/glyph_fell.toml"

[[files]]
file = "config/ars_nouveau/glyph_firework.toml"

[[files]]
file = "config/ars_nouveau/glyph_flare.toml"

[[files]]
file = "config/ars_nouveau/glyph_fortune.toml"

[[files]]
file = "config/ars_nouveau/glyph_freeze.toml"

[[files]]
file = "config/ars_nouveau/glyph_glide.toml"

[[files]]
file = "config/ars_nouveau/glyph_gravity.toml"

[[files]]
file = "config/ars_nouveau/glyph_grow.toml"

[[files]]
file = "config/ars_nouveau/glyph_gust.toml"

[[files]]
file = "config/ars_nouveau/glyph_harm.toml"

[[files]]
file = "config/ars_nouveau/glyph_harvest.toml"

[[files]]
file = "config/ars_nouveau/glyph_heal.toml"

[[files]]
file = "config/ars_nouveau/glyph_hex.toml"

[[files]]
file = "config/ars_nouveau/glyph_ignite.toml"

[[files]]
file = "config/ars_nouveau/glyph_infuse.toml"

[[files]]
file = "config/ars_nouveau/glyph_intangible.toml"

[[files]]
file = "config/ars_nouveau/glyph_interact.toml"

[[files]]
file = "config/ars_nouveau/glyph_invisibility.toml"

[[files]]
file = "config/ars_nouveau/glyph_launch.toml"

[[files]]
file = "config/ars_nouveau/glyph_leap.toml"

[[files]]
file = "config/ars_nouveau/glyph_light.toml"

[[files]]
file = "config/ars_nouveau/glyph_lightning.toml"

[[files]]
file = "config/ars_nouveau/glyph_linger.toml"

[[files]]
file = "config/ars_nouveau/glyph_name.toml"

[[files]]
file = "config/ars_nouveau/glyph_orbit.toml"

[[files]]
file = "config/ars_nouveau/glyph_pantomime.toml"

[[files]]
file = "config/ars_nouveau/glyph_phantom_block.toml"

[[files]]
file = "config/ars_nouveau/glyph_pickup.toml"

[[files]]
file = "config/ars_nouveau/glyph_pierce.toml"

[[files]]
file = "config/ars_nouveau/glyph_place_block.toml"

[[files]]
file = "config/ars_nouveau/glyph_prestidigitation.toml"

[[files]]
file = "config/ars_nouveau/glyph_projectile.toml"

[[files]]
file = "config/ars_nouveau/glyph_pull.toml"

[[files]]
file = "config/ars_nouveau/glyph_randomize.toml"

[[files]]
file = "config/ars_nouveau/glyph_redstone_signal.toml"

[[files]]
file = "config/ars_nouveau/glyph_rotate.toml"

[[files]]
file = "config/ars_nouveau/glyph_rune.toml"

[[files]]
file = "config/ars_nouveau/glyph_self.toml"

[[files]]
file = "config/ars_nouveau/glyph_sense_magic.toml"

[[files]]
file = "config/ars_nouveau/glyph_sensitive.toml"

[[files]]
file = "config/ars_nouveau/glyph_slowfall.toml"

[[files]]
file = "config/ars_nouveau/glyph_smelt.toml"

[[files]]
file = "config/ars_nouveau/glyph_snare.toml"

[[files]]
file = "config/ars_nouveau/glyph_split.toml"

[[files]]
file = "config/ars_nouveau/glyph_summon_decoy.toml"

[[files]]
file = "config/ars_nouveau/glyph_summon_steed.toml"

[[files]]
file = "config/ars_nouveau/glyph_summon_undead.toml"

[[files]]
file = "config/ars_nouveau/glyph_summon_vex.toml"

[[files]]
file = "config/ars_nouveau/glyph_summon_wolves.toml"

[[files]]
file = "config/ars_nouveau/glyph_toss.toml"

[[files]]
file = "config/ars_nouveau/glyph_touch.toml"

[[files]]
file = "config/ars_nouveau/glyph_underfoot.toml"

[[files]]
file = "config/ars_nouveau/glyph_wall.toml"

[[files]]
file = "config/ars_nouveau/glyph_wind_burst.toml"

[[files]]
file = "config/ars_nouveau/glyph_wind_shear.toml"

[[files]]
file = "config/ars_nouveau/glyph_wither.toml"

[[files]]
file = "config/ars_nouveau/reset.toml"

[[files]]
file = "config/ars_nouveau/rewind.toml"

[[files]]
file = "config/ars_nouveau/search_index/_7.cfe"

[[files]]
file = "config/ars_nouveau/search_index/_7.cfs"

[[files]]
file = "config/ars_nouveau/search_index/_7.si"

[[files]]
file = "config/ars_nouveau/search_index/segments_8"

[[files]]
file = "config/ars_nouveau/wololo.toml"

[[files]]
file = "config/auto-clicker-fabric.json"

[[files]]
file = "config/betterdays-client.toml"

[[files]]
file = "config/betterdays-common.toml"

[[files]]
file = "config/betterdungeons-neoforge-1_21.toml"

[[files]]
file = "config/bettermineshafts-neoforge-1_21.toml"

[[files]]
file = "config/betterstrongholds-neoforge-1_21.toml"

[[files]]
file = "config/betterstrongholds/README.txt"

[[files]]
file = "config/betterstrongholds/neoforge-1_21/README.txt"

[[files]]
file = "config/betterstrongholds/neoforge-1_21/armorstands.json"

[[files]]
file = "config/betterstrongholds/neoforge-1_21/itemframes.json"

[[files]]
file = "config/betterstrongholds/neoforge-1_21/ores.json"

[[files]]
file = "config/betterstrongholds/neoforge-1_21/rareblocks.json"

[[files]]
file = "config/biomesoplenty/biome_toggles.json"

[[files]]
file = "config/biomesoplenty/gameplay.toml"

[[files]]
file = "config/biomesoplenty/generation.toml"

[[files]]
file = "config/cat_loaf.json"

[[files]]
file = "config/clienttweaks-common.toml"

[[files]]
file = "config/comforts-common.toml"

[[files]]
file = "config/comforts-server.toml"

[[files]]
file = "config/companions-1.toml.bak"

[[files]]
file = "config/companions.toml"

[[files]]
file = "config/curios-client.toml"

[[files]]
file = "config/curios-common.toml"

[[files]]
file = "config/curios-server.toml"

[[files]]
file = "config/derk_easy_inventory_crafter.json"

[[files]]
file = "config/fastleafdecay-server.toml"

[[files]]
file = "config/fml.toml"

[[files]]
file = "config/inventoryessentials-common.toml"

[[files]]
file = "config/inventorysorter-client.toml"

[[files]]
file = "config/inventorysorter-server.toml"

[[files]]
file = "config/jei-server.toml"

[[files]]
file = "config/jei/blacklist.json"

[[files]]
file = "config/jei/ingredient-list-mod-sort-order.ini"

[[files]]
file = "config/jei/ingredient-list-type-sort-order.ini"

[[files]]
file = "config/jei/jei-client.ini"

[[files]]
file = "config/jei/jei-colors.ini"

[[files]]
file = "config/jei/jei-debug.ini"

[[files]]
file = "config/jei/jei-mod-id-format.ini"

[[files]]
file = "config/jei/recipe-category-sort-order.ini"

[[files]]
file = "config/knightlib-1.toml.bak"

[[files]]
file = "config/knightlib.toml"

[[files]]
file = "config/naturalist-server.toml"

[[files]]
file = "config/naturescompass-client.toml"

[[files]]
file = "config/naturescompass-common.toml"

[[files]]
file = "config/neoforge-client.toml"

[[files]]
file = "config/neoforge-common.toml"

[[files]]
file = "config/neoforge-server.toml"

[[files]]
file = "config/quickstack-client.toml"

[[files]]
file = "config/quickstack-common.toml"

[[files]]
file = "config/refurbished_furniture.client.toml"

[[files]]
file = "config/refurbished_furniture.server.toml"

[[files]]
file = "config/resourceful-config-web.json"

[[files]]
file = "config/sauce-server.toml"

[[files]]
file = "config/sauce-startup.toml"

[[files]]
file = "config/sereneseasons/fertility.toml"

[[files]]
file = "config/sereneseasons/seasons.toml"

[[files]]
file = "config/sky_aesthetics.json"

[[files]]
file = "config/smallships-client.toml"

[[files]]
file = "config/smallships-common.toml"

[[files]]
file = "config/sophisticatedbackpacks-common.toml"

[[files]]
file = "config/sophisticatedbackpacks-server.toml"

[[files]]
file = "config/sophisticatedcore-client.toml"

[[files]]
file = "config/sophisticatedcore-common.toml"

[[files]]
file = "config/stellaris-config.json"

[[files]]
file = "config/terrablender.toml"

[[files]]
file = "config/test-config.json"

[[files]]
file = "config/trashcans-common.toml"

[[files]]
file = "config/waystones-common.toml"

[[files]]
file = "config/whitenoise-client.toml"

[[files]]
file = "config/xaero/lib/client.cfg"

[[files]]
file = "config/xaero/lib/common.cfg"

[[files]]
file = "config/xaero/lib/profiles/default.cfg"

[[files]]
file = "config/xaero/lib/server_profiles/default.cfg"

[[files]]
file = "config/xaero/minimap/client.cfg"

[[files]]
file = "config/xaero/minimap/common.cfg"

[[files]]
file = "config/xaero/minimap/default_radar_categories_client.json"

[[files]]
file = "config/xaero/minimap/default_radar_categories_server.json"

[[files]]
file = "config/xaero/minimap/profiles/default.cfg"

[[files]]
file = "config/xaero/minimap/profiles/info_display_config/default.cfg.txt"

[[files]]
file = "config/xaero/minimap/server_profiles/default.cfg"

[[files]]
file = "config/xaero/world-map/client.cfg"

[[files]]
file = "config/xaero/world-map/common.cfg"

[[files]]
file = "config/xaero/world-map/profiles/default.cfg"

[[files]]
file = "config/xaero/world-map/server_profiles/default.cfg"

[[files]]
file = "config/xaerohud.txt"

[[files]]
file = "config/xaeropatreon.txt"

[[files]]
file = "icon.png"

[[files]]
file = "mods/ai-improvements.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/ars-elemental.pw.toml"
metafile = true

[[files]]
file = "mods/ars-nouveau.pw.toml"
metafile = true

[[files]]
file = "mods/auto-clicker.pw.toml"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
metafile = true

[[files]]
file = "mods/better-controls.pw.toml"
metafile = true

[[files]]
file = "mods/betterdays.pw.toml"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
metafile = true

[[files]]
file = "mods/brewin-and-chewin.pw.toml"
metafile = true

[[files]]
file = "mods/cat-jammies.pw.toml"
metafile = true

[[files]]
file = "mods/cat-loaf.pw.toml"
metafile = true

[[files]]
file = "mods/cfm-wap.pw.toml"
metafile = true

[[files]]
file = "mods/client-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
metafile = true

[[files]]
file = "mods/companions-mod.pw.toml"
metafile = true

[[files]]
file = "mods/critters-and-companions.pw.toml"
metafile = true

[[files]]
file = "mods/cultural-delights.pw.toml"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/expanded-delight.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
metafile = true

[[files]]
file = "mods/fast-leaf-decay.pw.toml"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
metafile = true

[[files]]
file = "mods/inventory-essentials.pw.toml"
metafile = true

[[files]]
file = "mods/inventory-sorter.pw.toml"
metafile = true

[[files]]
file = "mods/iron-chests.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/knight-lib.pw.toml"
metafile = true

[[files]]
file = "mods/mekanism-generators.pw.toml"
metafile = true

[[files]]
file = "mods/mekanism-tools.pw.toml"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
metafile = true

[[files]]
file = "mods/morecatvariants.pw.toml"
metafile = true

[[files]]
file = "mods/mrcrayfishs-furniture-mod-tools-refurbished.pw.toml"
metafile = true

[[files]]
file = "mods/naturalist.pw.toml"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
metafile = true

[[files]]
file = "mods/potentials.pw.toml"
metafile = true

[[files]]
file = "mods/quickstack-reborn.pw.toml"
metafile = true

[[files]]
file = "mods/refurbished-furniture.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/revamped-cats.pw.toml"
metafile = true

[[files]]
file = "mods/ribbits.pw.toml"
metafile = true

[[files]]
file = "mods/seamless-crafting.pw.toml"
metafile = true

[[files]]
file = "mods/serene-seasons.pw.toml"
metafile = true

[[files]]
file = "mods/small-ships.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
metafile = true

[[files]]
file = "mods/stellaris.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
metafile = true

[[files]]
file = "mods/trash-cans.pw.toml"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
metafile = true
