name = "Canth Server"
author = "Canth"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4f6f4a75dc180031ad782e51a63857f465e21fcb34c7cafa5c3e289d5661cf6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
