name = "Canth Server"
author = "Canth"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8289ae042feb5efc74e77c835f7cdd342cae009b0b6eb86e9d301d185695b890"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
